// Code generated by "stringer -type ColorType"; DO NOT EDIT.

package style

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NormalText-0]
}

const _ColorType_name = "Background"

var _ColorType_index = [...]uint8{0, 10}

func (i ColorType) String() string {
	if i < 0 || i >= ColorType(len(_ColorType_index)-1) {
		return "ColorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColorType_name[_ColorType_index[i]:_ColorType_index[i+1]]
}
